//Esta funcion evalua si el numero ingresado es o no un entero
int fnum(float x)
{
  int a = x;
  return a < x ? 1:0;
}



const char *facultades[12] =
{
"ESCUELA NACIONAL DE CIENCIAS DE LA TIERRA",
"ESCUELA NAL. DE ESTUDIOS SUP. UNIDAD JURIQUILLA",
"ESCUELA NAL. DE ESTUDIOS SUP. UNIDAD MERIDA",
"ESCUELA NAL. DE ESTUDIOS SUP. UNIDAD MORELIA",
"FACULTAD DE ARQUITECTURA",
"FACULTAD DE CIENCIAS",
"FACULTAD DE INGENIERIA",
"FACULTAD DE QUIMICA",
"FES ACATLAN",
"FES ARAGON",
"FES CUAUTITLAN",
"FES ZARAGOZA"
};



const char *carreras[32]=
      {
        "NULL",
        "ACTUARIA",
        "ARQUITECTURA",
        "ARQUITECTURA DE PAISAJE",
        "CIENCIAS DE LA COMPUTACION",
        "DISEÑO INDUSTRIAL",
        "FISICA",
        "INGENIERIA CIVIL",
        "INGENIERIA DE MINAS Y METALURGIA",
        "INGENIERIA ELECTRICA ELECTRONICA",
        "INGENIERIA EN COMPUTACION",
        "INGENIERIA GEOLOGICA",
        "INGENIERIA GEOFISICA",
        "INGENIERIA INDUSTRIAL",
        "INGENIERIA MECANICA",
        "INGENIERIA MECANICA ELECTRICA",
        "INGENIERIA PETROLERA",
        "INGENIERIA QUIMICA",
        "INGENIERIA QUIMICA METALURGICA",
        "INGENIERIA GEOMATICA",
        "MATEMATICAS APLICADAS Y COMPUTACION",
        "MATEMATICAS",
        "URBANISMO",
        "CIENCIAS DE LA TIERRA",
        "ING. EN TELECOMUNICACIONES, SISTEMAS Y ELECTRONICA",
        "GEOCIENCIAS",
        "TECNOLOGIAS PARA LA INFORMACION EN CIENCIAS",
        "CIENCIA DE MATERIALES SUSTENTABLES",
        "FISICA BIOMEDICA",
        "MATEMATICAS APLICADAS",
        "INGENIERIA AMBIENTAL",
        "INGENIERIA AEROESPACIAL"
      };


      int opciones[12][12] =
      {
        {23}, {23}, {23}, {24, 26},
        {22, 2, 3}, {1, 4,6,21,28,29},
        {7, 8, 9, 10, 11, 12, 13, 14, 16, 19, 30, 31},
        {17, 18}, {1, 2, 7, 20}, {2, 5, 7, 9, 10, 13, 14},
        {13, 15, 17, 24}, {17}

      };
